Contract_Management_V1-main/ContractManagementSystem/Models/Contract.cs
using ContractManagementSystem.Models.ContractManagement;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.General;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContractManagementSystem.Models
{
    public enum ContractStatus
    {
        Active, Pending, Rejected, Expired, Draft
    }
    public enum Predefined_ContractTypes
    {
        Joint_Venture,
        Non_Disclosure,
        Custom_Contract,
        Franchise,
        Intellectual_Property,
        Lease_Agreement,
        licensing_Agreement,
        Non_Complete,
        Permanent_Employment,
        Temporary_employment,
        Service,
        Procurement,
        Vendor,
    }

    public class Contract
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EffectiveDate { get; set; }

        [Required]

        [DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }

        /* [Required]
         public required string Parties { get; set; }*/
        [Required]
        public string? RequesterName { get; set; }
        [Required]
        [Column("RequestedDepartment")]
        public int DepartmentId { get; set; }
        public Department? Department { get; set; }



        [Required]
        public string? ContractType { get; set; }




        [Column("CreatorId")]
        public string? AppUserId { get; set; }
        public AppUser? AppUser { get; set; }

        public bool IsApprovalSent { get; set; } = false;
        [Required]
        public ContractStatus Status { get; set; } = ContractStatus.Draft;
        public DateTime CreationDate { get; set; } = DateTime.Now;

        public ICollection<Approval>? Approval { get; set; }
        public ICollection<ContractParty>? ContractParties { get; set; } // Navigation property
        public ICollection<Payment>? Payments { get; set; }
        public TerminationClause? TerminationClause { get; set; }
        public decimal ContractValue { get;  set; }
        public string ContractParty { get; set; }
        









    }
}

Contract_Management_V1-main/ContractManagementSystem/Models/ContractManagement/ContractType.cs
using System.ComponentModel.DataAnnotations;

namespace ContractManagementSystem.Models.ContractManagement
{
    public class ContractType
    {
        [Key]
        public int Id { get; set; } // Primary key
        public string Name { get; set; } // Name of the contract type, e.g., "Sales Contract", "Service Agreement", etc.
        public string Description { get; set; } // Description of the contract type
                                                // Other properties as needed

        // Navigation property to refer to associated workflows
        public ICollection<Workflow> Workflows { get; set; }
    }


}

Contract_Management_V1-main/ContractManagementSystem/Models/ContractTable.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace ContractManagementSystem.Models
{
    public class ContractTable
    {
        [Key]
        public required string ContractId { get; set; }

        public required string ContractedParty { get; set; }
        public required string ContractType { get; set; }
        public decimal ContractValue { get; set; }
        public required string PaymentStructure { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public ContractStatus Status { get; set; }
        public required string Action { get; set; } // Action buttons


        // Other properties removed for simplicity
    }

}

Contract_Management_V1-main/ContractManagementSystem/ViewModels/ContractSummaryViewModel.cs
using ContractManagementSystem.Services;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

public class CollaborationController : Controller
{
    private readonly ICollaborationService _collaborationService;
    private readonly IEmailService _emailService;

    public CollaborationController(ICollaborationService collaborationService, IEmailService emailService)
    {
        _collaborationService = collaborationService;
        _emailService = emailService;
    }

    [HttpPost]
    public async Task<IActionResult> AddCollaborator(int contractId, string email, int permissionLevel, bool notifyByEmail, string message)
    {
        // Add collaborator logic
        await _collaborationService.AddCollaboratorAsync(contractId, email, permissionLevel);

        if (notifyByEmail)
        {
            var subject = "Contract Collaboration";
            var body = $"You have been added as a collaborator for contract ID {contractId}. {message}";
            await _emailService.SendEmailAsync(email, subject, body);
        }

        return RedirectToAction("Index", "Contract");
    }
}

Contract_Management_V1-main/ContractManagementSystem/Controllers/ApprovalWorkflowController.cs
using ContractManagementSystem.Data;
using ContractManagementSystem.Models;
using Microsoft.AspNetCore.Mvc;

namespace ContractManagementSystem.Controllers
{
    public class ApprovalWorkflowController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private readonly ApplicationDbContext _context;
        private string signature;
        private string comments;

        public ApprovalWorkflowController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpPost]
        public ActionResult SubmitAprovalRequest(int ApproverId)
        {
            var ApprovalProcess = new ApprovalProcess
            {
                ApproverId = ApproverId,
                ContractStatus = "Approved",
                ApproverSignature = signature,
                ApproverComments = comments

            };
            _context.ApprovalProcesses.Add(ApprovalProcess);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");

        }
        [HttpPost]
        public ActionResult ApprovalStatus(int ApproverId, bool isApproved)
        {

            var clearanceProcess = _context.ApprovalProcesses.Find(ApproverId);

            if (isApproved)
            {
                ApprovalProcess.Status = "Approved by x"; // Update status
                                                          // Notify next approver ('y') via email or other means
            }
            else
            {
                ApprovalProcess.Status = "Rejected by x"; // Update status
                                                          // Notify employee and allow resubmission
            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Home");

        }
    }
}

Contract_Management_V1-main/ContractManagementSystem/Controllers/ContractController.cs
using ContractManagementSystem.Data;
using ContractManagementSystem.Models;
using ContractManagementSystem.Models.ContractManagement;
using ContractManagementSystem.Services;
using ContractManagementSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Microsoft.EntityFrameworkCore;

//using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

using static Microsoft.EntityFrameworkCore.DbLoggerCategory;


namespace ContractManagementSystem.Controllers
{

    public class ContractController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ContractService _contractService;
        private readonly UserManager<AppUser> _userManager;
        private readonly GetApproversService _getApproversService;
        private readonly IEmailService _emailService;
        private readonly IConfiguration _configuration;

        public ContractController(ContractService contractService, UserManager<AppUser> userManager,
               ApplicationDbContext db, GetApproversService getApproversService,
              IEmailService emailService, IConfiguration configuration)//dependency injection
        {

            this._contractService = contractService;
            _userManager = userManager;
            _context = db;
            _getApproversService = getApproversService;
            _emailService = emailService;
            _configuration = configuration;

        }


        public IActionResult ContractReports(Contract obj)
        {

            //get all information from contracts table
            IEnumerable<Contract> ContractList = _context.Contracts;


            return View(ContractList);

        }

        public IActionResult ContractTable()
        {
            return View();
        }

        public IActionResult ContractCount()
        {
            var counts = _contractService.GetContractCount();
            return View(counts);
        }
        private async Task<string> GetCurrentUserId()
        {

            var user = await _userManager.GetUserAsync(HttpContext.User);
            return user!.Id; //returns user id otherwise null. ? it wont throw an error if it is null

        }


        public IActionResult ContractPopup()
        {
           
        
            

            return PartialView("_ContractPopupPartial");
        }




        public IActionResult ApprovalWorkflow()
        {


            return View();

        }
       


        [HttpGet]
        public IActionResult CreateContract(string selectedContracts)
        {
            // Fetch the departments from the database
            var departments = _context.Departments.ToList();
            ViewBag.Departments = new SelectList(departments, "Id", "DepartmentName");

            // Initialize the view model
            var viewModel = new CreateContractVm();

            // Optionally handle the selected contracts here
            ViewBag.SelectedContracts = selectedContracts;

            return View(viewModel);
        }


        [HttpPost]
        
        public async Task<IActionResult> CreateContract(CreateContractVm obj)
        {
            if (ModelState.IsValid)
            {
                //nb obj.selecteddepartment returns the ID of department 
                var department = await _context.Departments.FirstOrDefaultAsync(d => d.Id == obj.SelectedDepartment);
                if (department == null)
                {
                    ModelState.AddModelError("SelectedDepartment", "Department not found.");
                    return View(obj);
                }



                //convert contract type to string.
                var contracttype_string = Enum.GetName(typeof(Predefined_ContractTypes), obj.ContractType);

                var contract = new Contract
                {
                    ContractType = contracttype_string,
                    RequesterName = obj.RequesterName,
                    EffectiveDate = obj.StartDate,
                    EndDate = obj.EndDate,
                    Status = ContractStatus.Draft,
                    IsApprovalSent = false,
                    AppUserId = await GetCurrentUserId(),
                    DepartmentId = department.Id,



                };
                _context.Contracts.Add(contract);
                await _context.SaveChangesAsync();

                int contractId = contract.Id; // take the contractid of that newly created contract
                obj.ContractId = contractId;//to use it in updating the contract in summary iaction
                var paymentstructure_string=Enum.GetName(typeof(Predefined_PaymentStructure), obj.PaymentStructure);
                var payment = new Payment
                {
                    ContractId = contractId,
                    PaymentStructure = paymentstructure_string,
                    Amount = obj.ContractValue,

                };
                _context.Payments.Add(payment);
                await _context.SaveChangesAsync();

                //create party record
                var party = new Party
                { //create party record
                    PartyName = obj.PartyName,
                    Email = obj.Email,
                };
                _context.Parties.Add(party);
                await _context.SaveChangesAsync();
                var partyId = party.Id;




                // Associate party with the contract
                var contractParty = new ContractParty
                {   //create contractparty records for this contract ,one contract having many parties
                    ContractId = contractId,
                    PartyId = partyId,


                };

                // Add party to the database
                _context.ContractParties.Add(contractParty);
                await _context.SaveChangesAsync();






                var terminationClause = new TerminationClause
                { //create terminationclause record for this contract
                    ContractId = contractId,
                    NoticePeriod = obj.TerminationNoticePeriod,

                };

                _context.TerminationClauses.Add(terminationClause);
                await _context.SaveChangesAsync();

                //create table to store contract documents 
                if (obj.ContractFile != null && obj.ContractFile.Length > 0)
                {
                    byte[] documentBytes = await ProcessFile(obj.ContractFile); //processing the file


                    // Now that you have the document bytes, you can create the ContractDocument object
                    var contractDocument = new ContractDocument
                    {
                        ContractId = contractId,
                        FileData = documentBytes
                    };

                    _context.ContractDocuments.Add(contractDocument);
                    await _context.SaveChangesAsync();

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "An error occurred.contractfile is empty");
                    return View(obj); // if there are errors return the model 
                }

                TempData["success"] = "Contract Creation Ok";
                return RedirectToAction("ContractSummary", new { id = obj.ContractId }); // if successful also pass the contracid 
            }
            // If ModelState is invalid, loop through model state errors and log them
            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    // Log or inspect the error message
                   // Console.WriteLine($"Error: {error.ErrorMessage}");
                    ModelState.AddModelError(string.Empty, error.ErrorMessage);
                }
            }
            
           
            return View(obj); // if there are errors return the model 
        }



        private async Task<byte[]> ProcessFile(IFormFile file)
        {
            byte[] documentBytes;
            using (var memoryStream = new MemoryStream())
            {
                await file.CopyToAsync(memoryStream);
                documentBytes = memoryStream.ToArray();
            }
            return documentBytes;
        }


        [HttpGet]
        public async Task<IActionResult> ContractSummary(int id)
        {
            var departments = _context.Departments.ToList();
            ViewBag.Departments = new SelectList(departments, "Id", "DepartmentName");
            var contract = await _context.Contracts //get that specific contract and include all related entries
                       .Include(c => c.Payments!)
              .Include(c => c.ContractParties!).ThenInclude(cp => cp.Party!) //include also the parties related to the contract
              .Include(c => c.TerminationClause!)
              .FirstOrDefaultAsync(c => c.Id == id);

            if (contract == null)
            {
                return NotFound();
            }

            //create a view model and get the details of that specific contract
            var viewModel = new CreateContractVm
            {
                ContractId = contract.Id,

                ContractType = (Predefined_ContractTypes)Enum.Parse(typeof(Predefined_ContractTypes),contract.ContractType),
                RequesterName = contract.RequesterName,
                StartDate = contract.EffectiveDate,
                EndDate = contract.EndDate,
                SelectedDepartment = contract.DepartmentId,
                ContractValue = (decimal)(contract.Payments?.FirstOrDefault()?.Amount ?? 0),
               // PaymentStructure = contract.Payments?.FirstOrDefault()?.PaymentStructure,
                PartyName = contract.ContractParties?.FirstOrDefault()?.Party?.PartyName,

Contract_Management_V1-main/ContractManagementSystem/Views/Contract/ActiveContracts.cshtml
@model List<Contract>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Active Contracts</title>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- DataTables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">

    <!-- DataTables Buttons CSS for Export -->
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css">

    <!-- Bootstrap CSS (Optional for better styling) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <main id="main" class="main">
        <h5>Active Contracts</h5>

        <table id="contractsTable" class="table table-striped">
            <thead>
                <tr>
                    <th>Contract ID</th>
                    <th>Contract Type</th>
                    <th>Requester Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var contract in Model)
                {
                    <tr>
                        <td>@contract.Id</td>
                        <td>@contract.ContractType</td>
                        <td>@contract.RequesterName</td>
                        <td>@contract.EffectiveDate.ToString("yyyy-MM-dd")</td>
                        <td>@contract.EndDate.ToString("yyyy-MM-dd")</td>
                        <td>@contract.Status</td>
                    </tr>
                }
            </tbody>
        </table>
    </main>

    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

    <!-- DataTables Buttons JS for Export -->
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>

    <!-- Bootstrap JS (Optional for better styling) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#contractsTable').DataTable({
                "pageLength": 10, // Set the number of entries per page
                "dom": 'Bfrtip', // 'B' for buttons, 'f' for search, 'r' for processing, 't' for table, 'i' for info, 'p' for pagination
                "buttons": [
                    {
                        extend: 'pdfHtml5',
                        text: 'Export to PDF',
                        title: 'Active Contracts Report',
                        exportOptions: {
                            columns: ':visible' // Export all visible columns
                        }
                    },
                    {
                        extend: 'excelHtml5',
                        text: 'Export to Excel',
                        title: 'Active Contracts Report',
                        exportOptions: {
                            columns: ':visible' // Export all visible columns
                        }
                    },
                    {
                        extend: 'print',
                        text: 'Print',
                        title: 'Active Contracts Report',
                        exportOptions: {
                            columns: ':visible' // Export all visible columns
                        }
                    }
                ]
            });
        });
    </script>
</body>
</html>

Contract_Management_V1-main/ContractManagementSystem/Views/Contract/ApprovalWorkflow.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Approvers</title>
    <link rel="stylesheet" href="~/UI_DEMO.styles.css" asp-append-version="true" />
    <link href="~/css/Approvers.css" rel="stylesheet">
    <script src="~/js/Approvers.js"></script>
</head>
<body>
    <main id="main" class="main">
        <div>
            <p>Approval Workflow</p>
        </div>

        <section class="section">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Workflow Name</h5>
                            <form asp-action="Index" method="post" class="row g-3">
                                <div class="col-md-12">
                                    <input type="text" class="form-control" placeholder="Eg. Purchase Agreement Approval">
                                </div>
                                <h5 class="card-title">Description</h5>
                                <div class="col-12">
                                    <div class="form-floating">
                                        <textarea class="form-control" placeholder="Address" id="floatingTextarea" style="height: 100px;"></textarea>
                                        <label for="floatingTextarea"></label>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <h5>Approval Type</h5>
                                    <div>
                                        <input type="radio" id="sequentialRadio" name="approvalType" value="sequential">
                                        <label for="sequentialRadio">Sequential</label>
                                    </div>
                                    <div>
                                        <input type="radio" id="parallelRadio" name="approvalType" value="parallel">
                                        <label for="parallelRadio">Parallel</label>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6">
                    <aside>
                        <div class="approval-cards-container">
                            <div class="card" id="sequentialCard">
                                <div class="card-header">
                                    <h5 class="card-title">Sequential Approval Workflow</h5>
                                </div>
                                <div class="card-body">
                                    <form asp-controller="ApprovalWorkflow" asp-action="SubmitAprovalRequest" method="post" id="approvalForm">
                                        <div>
                                            <label for="slaName">SLA Name:</label>
                                            <input type="text" id="slaName" name="slaName" required>
                                        </div>
                                        <div>
                                            <button type="button" class="btn btn-primary add-approver" onclick="addApprover()">Add Approver</button>
                                        </div>
                                        <ul id="approvers" class="approver-list">
                                            <!-- Approvers will be dynamically added here -->
                                        </ul>
                                        <div>
                                            <button type="submit" class="btn btn-success submit-btn">Submit</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- Popup content for Sequential Approval -->
                                <div id="sequentialPopup" class="popup-content" style="display: none;">
                                    <div class="modal-content">
                                        <span class="close" onclick="closeModal('sequentialPopup')">&times;</span>
                                        <h2>Add Approver</h2>
                                        <form>
                                            <input type="email" id="sequentialApproverEmail" placeholder="Enter Approver Email">
                                            <button type="button" class="btn" onclick="addApproverToSequential()">Add</button>
                                        </form>
                                    </div>
                                </div>
                            </div>

                            <div class="card parallel-approval-card">
                                <div class="card-body">
                                    <h6 class="card-title">Parallel Approval Workflow</h6>
                                    <form id="parallelApprovalForm">
                                        <div>
                                            <label for="parallelSlaName">SLA Name:</label>
                                            <input type="text" id="parallelSlaName" required>
                                        </div>
                                        <div>
                                            <button type="button" class="btn btn-primary add-approver" onclick="addParallelApprover()">Add Approver</button>
                                        </div>
                                        <ul id="parallelApprovers" class="approver-list">
                                            <!-- Parallel Approvers will be dynamically added here -->
                                        </ul>
                                        <div>
                                            <button type="submit" class="btn btn-success submit-btn">Submit</button>
                                        </div>
                                    </form>
                                </div>
                                <!-- Popup content for Parallel Approval -->
                                <div id="parallelPopup" class="popup-content" style="display: none;">
                                    <div class="modal-content">
                                        <span class="close" onclick="closeModal('parallelPopup')">&times;</span>
                                        <h2>Add Approver</h2>
                                        <form>
                                            <input type="email" id="parallelApproverEmail" placeholder="Enter Approver Email">
                                            <button type="button" class="btn" onclick="addApproverToParallel()">Add</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
        </section>
    </main>
</body>
</html>

Contract_Management_V1-main/ContractManagementSystem/Views/Contract/Confirmation.cshtml
<h1 class="text-info">CONTRACT CREATED SUCCESSFULLY</h1>
<button> <a asp-controller="Home" asp-action="Index" >Back To Homepage</a></button>

Contract_Management_V1-main/ContractManagementSystem/Views/Contract/ContractCount.cshtml
@model ( int ActiveCount, int PendingCount, int RejectedCount, int ExpiredCount,int DraftCount)

<main id="main" class="main">
<h1> contract counts</h1>
<p> total Active contracts:@Model.ActiveCount</p>
<p> total Pending contracts:@Model.PendingCount</p>
<p> total Rejected contracts:@Model.RejectedCount</p>
<p> total Expired contracts:@Model.ExpiredCount</p>
 <p> total Draft contracts:@Model.DraftCount</p>
</main>

Contract_Management_V1-main/ContractManagementSystem/Views/Contract/SelectApprover.cshtml
@using ContractManagementSystem.Models
@model Contract
@{
    ViewData["Title"] = "Select Approver";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <style>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
    body {
    background-color: #F7F4EB;
    }
    </style>
</head>
<body>


    </body>