Contract_Management_V1-main/ContractManagementSystem/Models/AdminProfile.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace ContractManagementSystem.Models
{
    public class AdminProfile : IdentityUser
    {
        [Required(ErrorMessage ="First Name is Required")]
        [Display(Name = "First Name")]
        public string? FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is Required")]
        [Display(Name = "Last Name")]
        public string? LastName { get; set; }

        [Required(ErrorMessage = "Employee Number is Required")]
        [Display(Name = "Employee Number")]
        public string? EmployeeNumber { get; set; }
        
        [Display(Name = "Authorization Level")]
        public string? AuthorizationLevel { get; set; }

        [Required(ErrorMessage = "Email is Required")]
        [Display(Name = "Email")]
        [EmailAddress]
        public override string? Email { get; set; }

        [Required(ErrorMessage = "Phone Number is Required")]
        [Display(Name = "Phone Number")]
        [Phone]
        public override string? PhoneNumber { get; set; }

        [Display(Name = "Alternative Phone Number")]
        [Phone]
        public string? AlternativePhoneNumber { get; set; }
    }
}

Contract_Management_V1-main/ContractManagementSystem/Models/VendorCompanyProfile.cs
namespace ContractManagementSystem.Models
{
    public class VendorCompanyProfile
    {
    }
}

Contract_Management_V1-main/ContractManagementSystem/Models/VendorIndividualProfile.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace ContractManagementSystem.Models
{
    public class VendorIndividualProfile
    {
        [Required(ErrorMessage = "Please enter your name.")]
        [Display(Name = "First Name")]
        public string? FirstName { get; set; }

        [Required(ErrorMessage = "Please enter your name.")]
        [Display(Name = "Last Name")]
        public string? LastName { get; set; }

        [Display(Name = "Other Name")]
        public string? OtherName { get; set; }

        [Required(ErrorMessage = "Please enter your email address.")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address.")]
        [Display(Name = "Email")]
        public string? Email { get; set; }

        [Display(Name = "Telephone Number")]
        public string? PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter your NHIF Number.")]
        [Display(Name = "NHIF Number")]
        [StringLength(12, MinimumLength = 10, ErrorMessage = "The {0} must be at least 10 characters long and not more than 15 characters.")]
        public string? NHIFNumber { get; set; }

        [Required(ErrorMessage = "Please enter your NSSF Number.")]
        [Display(Name = "NSSF Number")]
        [StringLength(12, MinimumLength = 10, ErrorMessage = "The {0} must be at least 10 characters long and not more than 15 characters.")]
        public string? NSSFNumber { get; set; }

        [Required(ErrorMessage = "Please enter your KRA Pin.")]
        [Display(Name = "KRA Pin")]
        [StringLength(12, MinimumLength = 10, ErrorMessage = "The {0} must be at least 10 characters long and not more than 15 characters.")]
        public string? KRAPin { get; set; }
    }
}

Contract_Management_V1-main/ContractManagementSystem/Controllers/AdminProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ContractManagementSystem.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using ContractManagementSystem.Data;
using ContractManagementSystem.ViewModels;

namespace ContractManagementSystem.Controllers
{
    public class AdminProfileController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly ApplicationDbContext _context;

        public AdminProfileController(UserManager<AppUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: AdminProfile/Edit




        public IActionResult UpdateProfile()
        {

            return View();
        }


        // POST: AdminProfile/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> UpdateProfile(AdminUpdateVM model)
        {
            if (ModelState.IsValid)
            {


                //Retrieve the current user
                var user = await _userManager.GetUserAsync(User);
                // var userId = user.Email;

                var admin = await _userManager.FindByEmailAsync(user.Email);
                //(v => v.Email == User.Identity!.Name);



                admin.FirstName = model.FirstName;

                admin.LastName = model.LastName;
                admin.EmployeeNumber = model.EmployeeNumber;
                admin.Email = model.Email;
                admin.PhoneNumber = model.PhoneNumber;
                //admin.AuthorizationLevel = model.AuthorizationLevel;
                admin.AlternativePhoneNumber = model.AlternativePhoneNumber;
                //admin.KraPin = model.KraPin;
                //admin.IdentificationNumber = model.IdentificationNumber;

                var result = await _userManager.UpdateAsync(admin);

                if (result.Succeeded)
                {
                    return RedirectToAction("ProfileUpdated");
                }
                else
                {
                    // Update operation failed
                    foreach (var error in result.Errors)
                    {
                        // Add model errors for each error
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View(model);





        }
    }
}

Contract_Management_V1-main/ContractManagementSystem/Controllers/UpdateProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Threading.Tasks;
using ContractManagementSystem.Models;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Formats.Jpeg;
using SixLabors.ImageSharp.PixelFormats;


namespace ContractManagementSystem.Controllers
{
    public class UpdateProfileController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public UpdateProfileController(UserManager<AppUser> userManager) : base()
        {
            _userManager = userManager;
        }

        public IActionResult AdminProfile()
        {
            return View();
        }

        public IActionResult VendorIndividualProfile()
        {
            return View();
        }

        public IActionResult VendorCompanyProfile()
        {
            return View();
        }

        //Users Profile
        public async Task<IActionResult> UsersProfile()
        {
            var user = await _userManager.GetUserAsync(User);
            var model = new AppUser
            {
                ProfilePicturePath = user.ProfilePicturePath,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UploadProfilePicture(IFormFile profileImage)
        {
            if (profileImage != null && profileImage.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await profileImage.CopyToAsync(memoryStream);
                    memoryStream.Position = 0; // Reset the stream position

                    // Load the image
                    using (var image = Image.Load(memoryStream))
                    {
                        // Check if the image is square
                        if (image.Width != image.Height)
                        {
                            // If not, crop it to make it square
                            var squareSize = Math.Min(image.Width, image.Height);
                            var x = (image.Width - squareSize) / 2;
                            var y = (image.Height - squareSize) / 2;

                            image.Mutate(ctx => ctx.Crop(new Rectangle(x, y, squareSize, squareSize)));
                        }

                        // Save the cropped image to a MemoryStream
                        using (var croppedStream = new MemoryStream())
                        {
                            image.SaveAsJpeg(croppedStream);
                            var imageBytes = croppedStream.ToArray();

                            var user = await _userManager.GetUserAsync(User);
                            user.ProfilePictureByteArray = imageBytes; // Save the cropped byte array
                            await _userManager.UpdateAsync(user);

                            return RedirectToAction("UsersProfile");
                        }
                    }
                }
            }

            // If no file was uploaded, return to the profile page without changes
            return RedirectToAction("UsersProfile");
        }


        public async Task<IActionResult> GetProfilePicture()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user.ProfilePictureByteArray != null)
            {
                return File(user.ProfilePictureByteArray, "image/jpeg");
            }

            //the default image is located in the wwwroot/images folder
            var defaultImagePath = Path.Combine("Project Images", "defaultProfile.jpeg");
            var defaultImage = System.IO.File.ReadAllBytes(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", defaultImagePath));

            // Return a default image if the user doesn't have a profile picture
            return File(defaultImage, "image/jpeg");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteProfilePicture()
        {
            var user = await _userManager.GetUserAsync(User);
            user.ProfilePictureByteArray = null; // Set the byte array to null to delete the picture
            await _userManager.UpdateAsync(user);

            return Ok(); // Return a success status
        }
    }
}

Contract_Management_V1-main/ContractManagementSystem/Controllers/VendorIndividualProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ContractManagementSystem.Models;
using ContractManagementSystem.ViewModels;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using ContractManagementSystem.Data;

namespace ContractManagementSystem.Controllers
{
    public class VendorIndividualProfileController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly ApplicationDbContext _context;

        public VendorIndividualProfileController(UserManager<AppUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: AdminProfile/Edit




        public IActionResult UpdateProfile()
        {

            return View();
        }


        // POST: AdminProfile/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> UpdateProfile(VendorIndividualProfileVM model)
        {
            if (ModelState.IsValid)
            {


                //Retrieve the current user
                var user = await _userManager.GetUserAsync(User);
                // var userId = user.Email;

                var vendor = await _userManager.FindByEmailAsync(user.Email);
                //(v => v.Email == User.Identity!.Name);



                vendor.FirstName = model.FirstName;

                vendor.LastName = model.LastName;
                vendor.OtherName = model.OtherName;
                vendor.Email = model.Email;
                vendor.PhoneNumber = model.PhoneNumber;
                vendor.NhifNumber = model.NhifNumber;
                vendor.NssfNumber = model.NssfNumber;
                vendor.KraPin = model.KraPin;
                vendor.IdentificationNumber = model.IdentificationNumber;

                var result = await _userManager.UpdateAsync(vendor);

                if (result.Succeeded)
                {
                    return RedirectToAction("ProfileUpdated");
                }
                else
                {
                    // Update operation failed
                    foreach (var error in result.Errors)
                    {
                        // Add model errors for each error
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }

            return View(model);





        }
    }
}

Contract_Management_V1-main/ContractManagementSystem/Views/UpdateProfile/AdminProfile.cshtml
@model ContractManagementSystem.Models.AdminProfile

@{
    ViewData["Title"] = "Admin Profile";
}
@{
   ViewBag.IncludeGlobalStyles = false;
}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css" rel="stylesheet">
<link rel="stylesheet" href="~/css/UpdateProfile.css" asp-append-version="true" />"

<main id="main" class="main">
<div class="main">
    <div class="container1">
        <h2>@ViewData["Title"]</h2>
    </div>
    <div class="form-container">
        <form asp-action="Edit" asp-controller="AdminProfile" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EmployeeNumber"></label>
                <input asp-for="EmployeeNumber" class="form-control" />
                <span asp-validation-for="EmployeeNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="AuthorizationLevel"></label>
                <select asp-for="AuthorizationLevel" class="form-control">
                    <option value="" selected disabled hidden>Select</option>
                    <option value="admin">Admin</option>
                    <option value="approver">Approver</option>
                </select>
                <span asp-validation-for="AuthorizationLevel" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="AlternativePhoneNumber"></label>
                <input asp-for="AlternativePhoneNumber" class="form-control" />
                <span asp-validation-for="AlternativePhoneNumber" class="text-danger"></span>
            </div>

                <div class="button-container">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <button type="button" id="cancelButton" class="btn btn-secondary">Cancel</button>
                </div>

        </form>
    </div>
</div>
</main>

<script>
    document.getElementById('cancelButton').addEventListener('click', function () {
        window.location.href = '@Url.Action("UsersProfile", "UpdateProfile")';
    });
</script>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Contract_Management_V1-main/ContractManagementSystem/Views/UpdateProfile/UsersProfile.cshtml
@using ContractManagementSystem.Models;

@{
    ViewData["Title"] = "Admin Profile";
}

@{
    ViewBag.IncludeGlobalStyles = false;
}

<title>@ViewData["Title"]</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

<style>
    h1 {
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 40px;
        font-weight: bolder;
        text-transform: uppercase;
    }
    h2{
        font-size: 10px;
    }
    .card-title {
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 15px;
        font-weight: bold;
        text-transform: uppercase;
    }

    .profile-picture-container {
        position: relative;
        display: inline-block;
        margin-right: 20px;
    }

    .profile-picture {
        width: 100px;
        height: 100px;
    }

    .profile-picture-edit-icon {
        position: absolute;
        top: 50%;
        right: 20%;
        transform: translate(-50%, -50%);
        font-size: 40px;
        color: #fff;
        cursor: pointer;
    }

    .profile-overview-container {
        display: flex;
        align-items: center;
        width: 80%;
    }

    .profile-overview-content {
        flex-grow: 1;
    }

    .dropdown-menu {
        display: none;
        position: absolute;
        background-color: #808080;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

        .dropdown-menu a {
            color: white;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

            .dropdown-menu a:hover {
                background-color: #A9A9A9;
            }
</style>
<body>
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Profile</h1>
        </div>

        <section class="section profile">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <h5 class="card-title">Profile Overview</h5>
                            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                                <div class="profile-picture-and-name d-flex flex-column align-items-center">
                                    <div class="profile-picture-container">
                                        <img src="@Url.Action("GetProfilePicture", "UpdateProfile")" alt="Profile Picture" class="rounded-circle">
                                        <i class="bi bi-camera profile-picture-edit-icon" onclick="toggleDropdown();"></i>
                                        <div id="dropdownMenu" class="dropdown-menu">
                                            <a href="#" onclick="editProfilePicture();">Edit Picture</a>
                                            <a href="#" onclick="deleteProfilePicture();">Delete Picture</a>
                                        </div>
                                    </div>
                                    <h2>@User.Identity!.Name</h2>
                                </div>
                                <br />
                                <div class="profile-overview-container">
                                    <div class="profile-overview-content">
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Full Name</div>
                                            <div class="col-lg-9 col-md-8">@User.Identity!.Name</div>
                                        </div>
                                        <br />
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Employee Number</div>
                                            <div class="col-lg-9 col-md-8">Lueilwitz, Wisoky and Leuschke</div>
                                        </div>
                                        <br />
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Authorization Level</div>
                                            <div class="col-lg-9 col-md-8">Web Designer</div>
                                        </div>
                                        <br />
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Email</div>
                                            <div class="col-lg-9 col-md-8">k.anderson@example.com</div>
                                        </div>
                                        <br />
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Phone</div>
                                            <div class="col-lg-9 col-md-8">(436) 486-3538 x29071</div>
                                        </div>
                                        <br />
                                        <div class="row">
                                            <div class="col-lg-3 col-md-4 label">Alternative Phone Number</div>
                                            <div class="col-lg-9 col-md-8">(436) 486-3538 x29071</div>
                                        </div>
                                        <br />
                                        <div class="text-center">
                                            <a href="@Url.Action("AdminProfile", "UpdateProfile")" class="btn btn-primary">Edit Profile</a>
                                        </div>
                                        <br />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <form method="post" enctype="multipart/form-data" asp-controller="UpdateProfile" asp-action="UploadProfilePicture" style="display: none;">
                            <input type="file" id="profileImage" name="profileImage" onchange="this.form.submit();">
                        </form>
                    </div>
                </div>


                <!-- Settings Card -->
               @*  <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-body pt-3">
                                <h5 class="card-title">Settings</h5>
                                <form>
                                    <div class="row mb-3">
                                        <label for="fullName" class="col-md-4 col-lg-3 col-form-label">Email Notifications</label>
                                        <div class="col-md-8 col-lg-9">
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="changesMade" checked>
                                                <label class="form-check-label" for="changesMade">
                                                    Changes made to your account
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="newProducts" checked>
                                                <label class="form-check-label" for="newProducts">
                                                    Information on new products and services
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="proOffers">
                                                <label class="form-check-label" for="proOffers">
                                                    Marketing and promo offers
                                                </label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="securityNotify" checked disabled>
                                                <label class="form-check-label" for="securityNotify">
                                                    Security alerts
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-primary">Save Changes</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div> *@

                <!-- Change Password Card -->
                <div class="row">
                    <div class="col-xl-12">
                        <div class="card">
                            <div class="card-body pt-3">
                                <h5 class="card-title">Change Password</h5>
                                <form>
                                    <div class="row mb-3">
                                        <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="password" type="password" class="form-control" id="currentPassword">
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="newpassword" type="password" class="form-control" id="newPassword">
                                        </div>
                                    </div>
                                    <div class="row mb-3">
                                        <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                                        <div class="col-md-8 col-lg-9">
                                            <input name="renewpassword" type="password" class="form-control" id="renewPassword">
                                        </div>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-primary">Change Password</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

    <script>
        function toggleDropdown() {
            document.getElementById('dropdownMenu').classList.toggle('show');
        }
        function editProfilePicture() {
            document.getElementById('profileImage').click();
        }

        function deleteProfilePicture() {
            if (confirm('Are you sure you want to delete your profile picture?')) {
                fetch('@Url.Action("DeleteProfilePicture", "UpdateProfile")', {
                    method: 'POST',
                    headers: {
                        'RequestVerificationToken': document.querySelector('input[name="__RequestVerificationToken"]').value
                    }
                }).then(response => {
                    if (response.ok) {
                        location.reload();
                    } else {
                        alert('Failed to delete profile picture.');
                    }
                });
            }
        }
    </script>
</body>